/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



package gui;
import java.awt.Graphics;
import java.awt.Color;
import moduladore.Modulador;
import moduladore.ModuladorAM;
import moduladore.ModuladorFM;
import senales.*;

/**
 *
 * @author Ruth Romero
 */
public class GUI extends javax.swing.JFrame {
    private double[] senalModuladora;
    private double[] senalPortadora;
    private double[] senalAM;
    private double[] senalFM;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bModular = new javax.swing.JButton();
        cbTipoSenal = new javax.swing.JComboBox<>();
        tAmpMod = new javax.swing.JTextField();
        tFrecMod = new javax.swing.JTextField();
        tFrecPort = new javax.swing.JTextField();
        tIndice = new javax.swing.JTextField();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de modulación AM/FM");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amplitud Moduladora");

        jLabel2.setText("Frecuencia Moduladora");

        jLabel3.setText("Frecuencia Portadora");

        jLabel4.setText("Índice");

        bModular.setBackground(new java.awt.Color(102, 153, 255));
        bModular.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bModular.setText("MODULAR");
        bModular.setToolTipText("");
        bModular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bModular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModularActionPerformed(evt);
            }
        });

        cbTipoSenal.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbTipoSenal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senoidal", "Cuadrangular", "Triangular" }));

        tAmpMod.setText("1");

        tFrecMod.setText("1");

        tFrecPort.setText("10");

        tIndice.setText("0.5");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tFrecPort, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFrecMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tAmpMod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tIndice))
                        .addGap(38, 38, 38)
                        .addComponent(cbTipoSenal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bModular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tAmpMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoSenal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tFrecMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tFrecPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(bModular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bModularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModularActionPerformed
        // TODO add your handling code here:
        double A = Double.parseDouble(tAmpMod.getText());
        double fm = Double.parseDouble(tFrecMod.getText());
        double fc = Double.parseDouble(tFrecPort.getText());
        double indice = Double.parseDouble(tIndice.getText());

        Senal moduladora;//inicializar
        moduladora = switch (cbTipoSenal.getSelectedIndex()) {
            case 0 -> new SenalSenoidal(A, fm);
            case 1 -> new SenalCuadrada(A, fm);
            case 2 -> new SenalTriangular(A, fm);
            default -> new SenalSenoidal(A, fm);
        };

        Senal portadora = new SenalSenoidal(1, fc);//inicializar

        moduladora.generar();
        portadora.generar();
        
        senalModuladora = moduladora.getValores();//cargar
        senalPortadora = portadora.getValores();//cargar
        
        Modulador modAM = new ModuladorAM(indice);//inicializar modulador AM
        Modulador modFM = new ModuladorFM(indice);//inicializar modulador FM
        
        //modular AM
        senalAM = modAM.modular(senalPortadora,senalModuladora,portadora.getTiempo());
        //modular FM
        senalFM = modFM.modular(senalPortadora,senalModuladora,portadora.getTiempo());
        
        dibujarSenales();
    }//GEN-LAST:event_bModularActionPerformed
    
    private void dibujarSenales() {
        Graphics g = panel.getGraphics();

        int w = panel.getWidth();
        int h = panel.getHeight();

        //fondo blanco
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, w, h);

        //separación entre señales
        int separacion = 80;

        //títulos
        g.setColor(Color.BLACK);

        dibujar(g, senalModuladora, 40, Color.BLUE);
        g.drawString("Moduladora", 20, 10);
        
        dibujar(g, senalPortadora, 40 + separacion, Color.RED);
        g.drawString("Portadora", 20, 10 + separacion);

        dibujar(g, senalAM, 40 + separacion * 2, Color.GREEN);
        g.drawString("AM", 20, 10 + separacion * 2);

        dibujar(g, senalFM, 40 + separacion * 3, Color.MAGENTA);
        g.drawString("FM", 20, 10 + separacion * 3);
    }
    
    private void dibujar(Graphics g, double[] datos, int offsetY, Color color) {
        int w = panel.getWidth();

        //eje horizontal
        g.setColor(Color.LIGHT_GRAY);
        g.drawLine(0, offsetY, w, offsetY);

        //señal
        g.setColor(color);

        int escalaY = 20;

        int prevX = 0;
        int prevY = offsetY;

        for (int i = 0; i < datos.length; i++) {

            int x = i * w / datos.length;
            int y = offsetY - (int)(datos[i] * escalaY);

            g.drawLine(prevX, prevY, x, y);

            prevX = x;
            prevY = y;
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModular;
    private javax.swing.JComboBox<String> cbTipoSenal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tAmpMod;
    private javax.swing.JTextField tFrecMod;
    private javax.swing.JTextField tFrecPort;
    private javax.swing.JTextField tIndice;
    // End of variables declaration//GEN-END:variables
}
