name: Generar UML Automático

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Descargar Motor Oficial de PlantUML
      run: |
        wget https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar -O plantuml.jar

    - name: Ingeniería Inversa y Renderizado
      run: |
        # Forzamos a PlantUML a escanear el código y guardar el resultado directamente en la raíz como diagrama.png
        java -jar plantuml.jar "Modulador/src/" -tpng -output "."
        
        # El comando anterior genera un archivo llamado src.png en la raíz. Lo renombramos a diagrama.png de forma segura:
        if [ -f src.png ]; then
          mv src.png diagrama.png
        elif [ -f Modulador/src/src.png ]; then
          mv Modulador/src/src.png diagrama.png
        fi

    - name: Subir cambios al repositorio de GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add diagrama.png || echo "No se pudo añadir el archivo"
        git commit -m "Bot: Actualización automática del diagrama UML [skip ci]" || echo "No hay cambios en el diagrama"
        git push