name: Generar UML
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Descargar PlantUML
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar -O plantuml.jar
      
      - name: Generar Imagen
        # Esto guarda el archivo explícitamente en la raíz con el nombre diagrama.png
        run: java -jar plantuml.jar diagrama.puml -o .
        
      - name: Subir cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add diagrama.png
          git commit -m "Actualizar diagrama [skip ci]" || echo "No hay cambios para subir"
          git push