name: Generar UML Automático

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Ingeniería Inversa (Java a PlantUML)
      run: |
        wget https://github.com/dbalek/puml-gen/releases/download/v1.0.0/puml-gen-1.0.0.jar -O puml-gen.jar
        # Escaneamos la carpeta src de tu proyecto NetBeans dentro de Modulador
        java -jar puml-gen.jar Modulador/src/ > diagrama.puml

    - name: Renderizar archivo .puml a imagen PNG (Oficial)
      uses: plantuml/plantuml-github-action@main
      with:
        args: -tpng diagrama.puml

    - name: Subir cambios al repositorio de GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add diagrama.puml diagrama.png
        git commit -m "Bot: Actualización automática del diagrama UML [skip ci]" || echo "No hay cambios en el diagrama"
        git push